version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=starburger
      - POSTGRES_USER=Vitaliusius
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always

    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./frontend/bundles:/app/bundles
      - ./frontend/assets:/app/assets
      - media_caravan:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


volumes:
  postgres_data:
  media_caravan: