# Generated by Django 5.2.14 on 2026-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('online', 'Онлайн'), ('cash', 'Наличными')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
