# Generated by Django 5.2.15 on 2026-07-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн'), ('cash', 'Наличными')], db_index=True, max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
