# Generated by Django 5.2.14 on 2026-06-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_remove_order_products_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderelements',
            old_name='products',
            new_name='product',
        ),
    ]
