# Generated by Django 5.2.14 on 2026-06-19 11:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderelements_order_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('assembly', 'В сборке'), ('delivery', 'В пути'), ('completed', 'Доставлен')], db_index=True, default='new', max_length=15, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(db_index=True, max_length=200, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='firstname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
    ]
