# Generated by Django 5.2.15 on 2026-07-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='request_at',
            new_name='request_date',
        ),
    ]
